### ISSUE TITLE
The SDK does not work with `moduleResolution` set to "node" in Next.js tsconfig

### ISSUE THREAD

**Issue by Jonath-z** [dfinity/verifiable-credentials-sdk#48] opened 2024-08-07 20:44 UTC
I'm implementing VC from a relying party written in TypeScript with Next.js, Setting up the module resolution to bundler the app works without problem, however it's mendatory for the `moduleResolution` to match the webpack in Next.js which is `node`. 
When running `next build` command next reset `moduleResolution` to node in `tsconfig`  which causes the app to break.

Node: v22
Next: 13.2.4
TypeScript: 5.0.2

**Comment by lmuntaner** [comment] 2024-08-27 08:09
Thanks for reporting the issue.

I'll try to fix it.

**Comment by lmuntaner** [comment] 2024-08-27 12:25
Hi @Jonath-z 

I set up a new NextJS project and I was able to install and use the SDK.

One can't import directly from the library, there is no entry point. You need to import the module you want:

```
// import * from '@dfinity/verifiable-credentials'; // Error: use sub-imports, to ensure small app size
import { requestVerifiablePresentation } from "@dfinity/verifiable-credentials/request-verifiable-presentation";
```

Maybe this is the problem?

Otherwise, could you share your `tsconfig.json` or the project reproducing the issue so that I'll try to reproduce it locally, thanks!

**Comment by Jonath-z** [comment] 2024-08-27 13:29
@lmuntaner this is the project at the exact PR I'm experementing the VC feature: https://github.com/dacadeorg/dacade-frontend-app/pull/1284

This following is the error I'm getting when building the project with ` "moduleResolution": "node",`
![Screenshot from 2024-08-27 15-28-45](https://github.com/user-attachments/assets/415e9722-332c-4f05-b8ab-a10a2a7c449d)

**Comment by lmuntaner** [comment] 2024-08-27 15:09
Did you try with `"moduleResolution": "bundler"`. Or do you need to support only `require` for some reason?

`"node"` seems to be outdated:

> 'node10' (previously called 'node') for Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code.

Reference: https://www.typescriptlang.org/tsconfig/#moduleResolution

**Comment by Jonath-z** [comment] 2024-08-29 09:41
I tried with `"moduleResolution": "bundler"` but nextjs requires `"moduleResolution": "node"` to work properly, the module resolution is being reset to node before building the project

**Comment by lmuntaner** [comment] 2024-08-29 12:53
Which NextJS version is that?

I recently created a new project from NextJS, and it used `"moduleResolution": "bundler"`.

**Comment by lmuntaner** [comment] 2024-08-30 07:50
I can't run `npm install` without errors. Which `node` version are you using, I tried with v20 and v18.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: dacade@1.8.2
npm ERR! Found: typescript@5.0.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"5.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@">=5.0.4" from viem@1.21.4
npm ERR! node_modules/viem
npm ERR!   viem@"^1.18.1" from the root project
npm ERR!   peer viem@">=1 <2" from @web3modal/wagmi@3.5.7
npm ERR!   node_modules/@web3modal/wagmi
npm ERR!     @web3modal/wagmi@"^3.2.0" from the root project
npm ERR!   1 more (@wagmi/core)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/llorencmuntaner/.npm/_logs/2024-08-30T07_49_29_109Z-eresolve-report.txt
```

**Comment by peterpeterparker** [comment] 2024-09-03 15:56
I don't particularly like this solution, but since your setup doesn't seem to resolve the `exports` field in `package.json`, you can try pointing directly to the library:

```
import { requestVerifiablePresentation, type VerifiablePresentationResponse } from "@dfinity/verifiable-credentials/dist/request-verifiable-presentation";
```

I just cloned your branch and tried it out, it seems to have resolved the build issue but, I let you confirm.

**Comment by Jonath-z** [comment] 2024-09-06 09:39
@peterpeterparker with this approach the app breaks
![Screenshot from 2024-09-06 11-38-50](https://github.com/user-attachments/assets/4de547cb-1aca-4e00-b431-aaeb6ab9de91)

**Comment by peterpeterparker** [comment] 2024-09-08 10:04
I made a few modifications to the way we package the library (PR #56). Therefore, @Jonath-z, please try the following `next` version:

```
yarn add @dfinity/verifiable-credentials@next
```

As far as I can tell, the issue is resolved, and my editor is not reporting any errors.

I got issues at runtime but, the all errors mention Firebase therefore unrelated to the library.

<img width="1536" alt="Capture d’écran 2024-09-08 à 11 59 14" src="https://github.com/user-attachments/assets/d8c68929-d364-486c-9b1c-486c369e6ade">
<img width="1536" alt="Capture d’écran 2024-09-08 à 11 59 54" src="https://github.com/user-attachments/assets/46046c18-c74c-472b-876d-13b09d87fb39">
<img width="1536" alt="Capture d’écran 2024-09-08 à 11 59 57" src="https://github.com/user-attachments/assets/97dae71f-b29a-47e3-9f1e-4ecdd1a9a279">
<img width="1536" alt="Capture d’écran 2024-09-08 à 12 01 30" src="https://github.com/user-attachments/assets/4a28abab-3073-40c6-94cb-e491e8792231">

**Comment by lmuntaner** [comment] 2024-09-09 08:18
@Jonath-z could you try two versions we published?

* [0.0.3-next-2024-09-09](https://www.npmjs.com/package/@dfinity/verifiable-credentials/v/0.0.3-next-2024-09-09)
* [0.0.3-next-2024-09-08.1](https://www.npmjs.com/package/@dfinity/verifiable-credentials/v/0.0.3-next-2024-09-08.1)

You can install a specific version with:

```
npm install @dfinity/verifiable-credentials@0.0.3-next-2024-09-09
```

Let us now after you test those, thanks!

**Comment by Jonath-z** [comment] 2024-09-09 09:13
@peterpeterparker @lmuntaner this version works ` "@dfinity/verifiable-credentials": "^0.0.3-next-2024-09-09"`

**Comment by lmuntaner** [comment] 2024-09-09 10:22
@Jonath-z did you try also [0.0.3-next-2024-09-08.1](https://www.npmjs.com/package/@dfinity/verifiable-credentials/v/0.0.3-next-2024-09-08.1) ? We prefer that solution.

**Comment by Jonath-z** [comment] 2024-09-09 10:29
@lmuntaner  I just tried it and this is the result: 
![Screenshot from 2024-09-09 12-26-36](https://github.com/user-attachments/assets/6ea3b224-fbb8-4022-8955-e7972d968882)

**Comment by peterpeterparker** [comment] 2024-09-09 10:34
> I just tried it and this is the result:

@Jonath-z this error is expected. With `0.0.3-next-2024-09-08.1` you should stick to the original import as on main:

```
import { requestVerifiablePresentation, type VerifiablePresentationResponse } from "@dfinity/verifiable-credentials/request-verifiable-presentation";
```

i.e. `@dfinity/verifiable-credentials/request-verifiable-presentation` and not `@dfinity/verifiable-credentials`.

Sorry if it wasn't well communicated.

**Comment by Jonath-z** [comment] 2024-09-10 09:05
> > I just tried it and this is the result:
> 
> @Jonath-z this error is expected. With `0.0.3-next-2024-09-08.1` you should stick to the original import as on main and as in your branch:
> 
> ```
> import { requestVerifiablePresentation, type VerifiablePresentationResponse } from "@dfinity/verifiable-credentials/request-verifiable-presentation";
> ```
> 
> i.e. `@dfinity/verifiable-credentials/request-verifiable-presentation` and not `@dfinity/verifiable-credentials`.
> 
> Sorry if it wasn't well communicated.

@peterpeterparker following this works

**Comment by peterpeterparker** [comment] 2024-09-10 09:30
Awesome, @Jonath-z! Great to hear. I've merged our PR.

@lmuntaner will handle releasing a version, and once that's done, we can close this issue.

Thanks for your help!

**Comment by lmuntaner** [comment] 2024-09-10 12:57
@Jonath-z I release a new version `0.4.0`. If you install it it should work as like the following:

```
import { requestVerifiablePresentation, type VerifiablePresentationResponse } from "@dfinity/verifiable-credentials/request-verifiable-presentation";
```

If you confirm that it's working, we'll close this issue.

Thanks!

**Comment by Jonath-z** [comment] 2024-09-10 15:05
@lmuntaner I can confirm that the release works `0.0.4`

**Comment by lmuntaner** [comment] 2024-09-10 17:27
Thanks for confirming @Jonath-z !

Issue fixed in new version `.0.0.4`

**Closed by lmuntaner** 2024-09-10 17:27 UTC
